{{- if not (.Values.isLB) }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jpetstoreweb
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  labels:
    app: jpetstoreweb
spec:
  rules:
  - host: {{ .Values.httpHost }}
    http:
      paths:
      - backend:
          serviceName: web
          servicePort: 80
        path: /
{{- end }}
